# version: "3.9"

services:
  web:
    build: .
    user: "node:node"
    env_file:
      - .env
    # environment:
    #   - APP_PORT=${APP_PORT:-3000}
    #   - MONGO_URI=${MONGO_URI}
    #   - FRONTEND_URL=${FRONTEND_URL}      
    #   # - DB_URI=redis://db:6379
    #   - JWT_SECRET=${JWT_SECRET}
    #   - ENV=${ENV}
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  # db:
  #   image: "redis:${IMAGE_VERSION_REDIS:-7.0.9-bullseye}"
  #   ports:
  #     - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: